<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hello_complete</name>
   <tag></tag>
   <elementGuidId>eaa7218c-bb87-4d54-8e81-ab49b0553a61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='todo']/li/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.complete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#todo >> internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8b73e65-7d31-45d1-ba3b-1bcf8b3f8859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>complete</value>
      <webElementGuid>51f8ae2d-1c19-4d0a-a021-1e3dc6926db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todo&quot;)/li[1]/div[@class=&quot;buttons&quot;]/button[@class=&quot;complete&quot;]</value>
      <webElementGuid>396ff83f-1b9b-407e-9a11-d592349fb3a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='todo']/li/div/button[2]</value>
      <webElementGuid>ae564928-c093-493c-95ef-2111a59250fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello'])[1]//button[2]</value>
      <webElementGuid>b1dd5492-d63f-47a5-9dc5-62c6940d0855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/following::button[2]</value>
      <webElementGuid>65f3171c-eef8-432a-a370-97c7eafea9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compeleted Tasks'])[1]/preceding::button[1]</value>
      <webElementGuid>fb550a99-0b35-4143-b449-5335065c1a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unmark All'])[1]/preceding::button[1]</value>
      <webElementGuid>0206213e-de7a-4305-853b-10192e0846c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/button[2]</value>
      <webElementGuid>47f3419b-7a16-4e9a-a7e7-d07bbb655896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
