<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Task 2Task 1</name>
   <tag></tag>
   <elementGuidId>4cc311ce-61f8-4b5f-9e6d-7c5422119a51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='todo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#todo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Task 2Task 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>01acdb49-b4c6-4bd3-8101-9fbb6c76ae6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>todo</value>
      <webElementGuid>201afe71-8425-4387-89c0-15ce91783077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>todo</value>
      <webElementGuid>e675d371-669e-4ae8-af60-4162035f9f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Task 2Task 1</value>
      <webElementGuid>a175e6ec-faf8-4d57-bc24-3231c6e87b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;todo&quot;)</value>
      <webElementGuid>e01a9a06-81c7-4421-87ca-0fc7866fe941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='todo']</value>
      <webElementGuid>233503be-bcae-4bda-ac48-25248d7fb8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/following::ul[1]</value>
      <webElementGuid>c13e4dd0-954e-4260-9001-6af34fc0a333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark All'])[1]/following::ul[1]</value>
      <webElementGuid>7f29a035-d20e-46e8-b08f-99a383274847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>dff9b165-d331-43c4-b029-412d7aa1b94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'todo' and (text() = 'Task 2Task 1' or . = 'Task 2Task 1')]</value>
      <webElementGuid>11ad86a7-f0db-47be-84d2-04c6b68ea063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
